swagger: "2.0"
info:
  description: This is the swagger file that goes with the server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:  
  - "application/json"

basePath: "/api"

# Paths supported by the server app
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Read the entire set of people
      description: Read the set of people
      responses:
        200:
          description: Successfully read the set of people
          schema:
            type: array
            items:
              properties:
                person_id:
                  type: integer
                  description: Id of the person
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the person's record

    post:
      operationId: people.add_one
      tags: 
        - People
      summary: Add person's data to the people list
      description: Add a person's data to the people list
      parameters:
        - name: person
          in: body
          description: A person to add
          required: true
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        201:
          description: Successfully add a person to the people set
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

  /people/{person_id}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: Read one person's data from the people set
      description: Read one person's data from the people set
      parameters:
        - name: person_id
          in: path
          description: ID of the person to look up in the db
          type: integer
          required: true
      responses:
        200:
          description: Successfully read one person's data from the people set
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record
    
    put:
      operationId: people.update_one
      tags:
        - People
      summary: Update person's data in the set
      description: Update person's data in the set
      parameters:
        - name: person_id
          in: path
          description: ID of the person whose data is to be updated in the set
          type: integer
          required: true
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
      responses:
        200:
          description: Successfully updated person's data in the people set
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person in the database
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record
    
    delete:
      operationId: people.delete_one
      tags:
        - People
      summary: Delete person's data from the people set
      description: Delete person's data from the people set
      parameters:
        - name: person_id
          in: path
          description: ID of the person whose data to be deleted in the set
          type: integer
          required: true
      responses:
        200:
          description: Successfully deleted person's info from the people set
